#!/bin/sh

name="$1"
comport="$2"
pipe=$(powershell.exe \(Get-VMComPort -VMName "$name" -Number "$comport"\).Path | tr '\\' / | tr -d '\r')

exec socat EXEC:"npiperelay.exe -ei $pipe" STDIO,rawer,escape=0xf
